exports.itemdex = {
1:{name:"Ability Capsule",type:"hold"},
2:{name:"Ability Urge",type:"battle"},
3:{name:"Abomasite",type:"hold"},
4:{name:"Absolite",type:"hold"},
5:{name:"Absorb Bulb",type:"hold"},
6:{name:"Adamant Orb",type:"hold"},
7:{name:"Adventure Rules",type:"general"},
8:{name:"Aerodactylite",type:"hold"},
9:{name:"Aggronite",type:"hold"},
10:{name:"Aguav Berry",type:"berries"},
11:{name:"Air Balloon",type:"hold"},
12:{name:"Alakazite",type:"hold"},
13:{name:"Ampharosite",type:"hold"},
14:{name:"Amulet Coin",type:"hold"},
15:{name:"Antidote",type:"medicine"},
16:{name:"Apicot Berry",type:"berries"},
17:{name:"Armor Fossil",type:"general"},
18:{name:"Aspear Berry",type:"berries"},
19:{name:"Awakening",type:"medicine"},
20:{name:"Babiri Berry",type:"berries"},
21:{name:"BalmMushroom",type:"general"},
22:{name:"Banettite",type:"hold"},
23:{name:"Belue Berry",type:"berries"},
24:{name:"Berry Juice",type:"medicine"},
25:{name:"Big Mushroom",type:"general"},
26:{name:"Big Nugget",type:"general"},
27:{name:"Big Pearl",type:"general"},
28:{name:"Big Root",type:"hold"},
29:{name:"Binding Band",type:"hold"},
30:{name:"Black Belt",type:"hold"},
31:{name:"Black Flute",type:"general"},
32:{name:"Black Sludge",type:"hold"},
33:{name:"BlackGlasses",type:"hold"},
34:{name:"Blastoisinite",type:"hold"},
35:{name:"Blazikenite",type:"hold"},
36:{name:"Blk Apricorn",type:"general"},
37:{name:"Blu Apricorn",type:"general"},
38:{name:"Blue Flute",type:"general"},
39:{name:"Blue Scarf",type:"general"},
40:{name:"Blue Shard",type:"general"},
41:{name:"Bluk Berry",type:"berries"},
42:{name:"BrightPowder",type:"hold"},
43:{name:"Bug Gem",type:"hold"},
44:{name:"Burn Drive",type:"hold"},
45:{name:"Burn Heal",type:"medicine"},
46:{name:"Calcium",type:"medicine"},
47:{name:"Carbos",type:"medicine"},
48:{name:"Casteliacone",type:"medicine"},
49:{name:"Cell Battery",type:"hold"},
50:{name:"Charcoal",type:"hold"},
51:{name:"Charizardite X",type:"hold"},
52:{name:"Charizardite Y",type:"hold"},
53:{name:"Charti Berry",type:"berries"},
54:{name:"Cheri Berry",type:"berries"},
55:{name:"Cherish Ball",type:"pokeballs"},
56:{name:"Chesto Berry",type:"berries"},
57:{name:"Chilan Berry",type:"berries"},
58:{name:"Chill Drive",type:"hold"},
59:{name:"Choice Band",type:"hold"},
60:{name:"Choice Scarf",type:"hold"},
61:{name:"Choice Specs",type:"hold"},
62:{name:"Chople Berry",type:"berries"},
63:{name:"Claw Fossil",type:"general"},
64:{name:"Cleanse Tag",type:"hold"},
65:{name:"Clever Wing",type:"medicine"},
66:{name:"Coba Berry",type:"berries"},
67:{name:"Colbur Berry",type:"berries"},
68:{name:"Colress Machine",type:"hold"},
69:{name:"Comet Shard",type:"general"},
70:{name:"Cornn Berry",type:"berries"},
71:{name:"Cover Fossil",type:"general"},
72:{name:"Custap Berry",type:"berries"},
73:{name:"DNA Splicers",type:"general"},
74:{name:"Damp Mulch",type:"general"},
75:{name:"Damp Rock",type:"hold"},
76:{name:"Dark Gem",type:"hold"},
77:{name:"Dawn Stone",type:"general"},
78:{name:"DeepSeaScale",type:"hold"},
79:{name:"DeepSeaTooth",type:"hold"},
80:{name:"Destiny Knot",type:"hold"},
81:{name:"Dire Hit",type:"battle"},
82:{name:"Dive Ball",type:"pokeballs"},
83:{name:"Dome Fossil",type:"general"},
84:{name:"Douse Drive",type:"hold"},
85:{name:"Draco Plate",type:"hold"},
86:{name:"Dragon Fang",type:"hold"},
87:{name:"Dragon Gem",type:"hold"},
88:{name:"Dragon Scale",type:"general"},
89:{name:"Dread Plate",type:"hold"},
90:{name:"Dream Ball",type:"pokeballs"},
91:{name:"Dropped Item",type:"hold"},
92:{name:"Dubious Disc",type:"general"},
93:{name:"Durin Berry",type:"berries"},
94:{name:"Dusk Ball",type:"pokeballs"},
95:{name:"Dusk Stone",type:"general"},
96:{name:"Earth Plate",type:"hold"},
97:{name:"Eject Button",type:"hold"},
98:{name:"Electirizer",type:"general"},
99:{name:"Electric Gem",type:"hold"},
100:{name:"Elevator Key",type:"hold"},
101:{name:"Elixir",type:"medicine"},
102:{name:"Energy Root",type:"medicine"},
103:{name:"EnergyPowder",type:"medicine"},
104:{name:"Enigma Berry",type:"berries"},
105:{name:"Escape Rope",type:"general"},
106:{name:"Ether",type:"medicine"},
107:{name:"Everstone",type:"hold"},
108:{name:"Eviolite",type:"hold"},
109:{name:"Exp. Share",type:"hold"},
110:{name:"Expert Belt",type:"hold"},
111:{name:"Fairy Gem",type:"general"},
112:{name:"Fast Ball",type:"pokeballs"},
113:{name:"Fighting Gem",type:"hold"},
114:{name:"Figy Berry",type:"berries"},
115:{name:"Fire Gem",type:"hold"},
116:{name:"Fire Stone",type:"general"},
117:{name:"Fist Plate",type:"hold"},
118:{name:"Flame Orb",type:"hold"},
119:{name:"Flame Plate",type:"hold"},
120:{name:"Float Stone",type:"hold"},
121:{name:"Fluffy Tail",type:"general"},
122:{name:"Flying Gem",type:"hold"},
123:{name:"Focus Band",type:"hold"},
124:{name:"Focus Sash",type:"hold"},
125:{name:"Fresh Water",type:"medicine"},
126:{name:"Friend Ball",type:"pokeballs"},
127:{name:"Full Heal",type:"medicine"},
128:{name:"Full Incense",type:"hold"},
129:{name:"Full Restore",type:"medicine"},
130:{name:"Ganlon Berry",type:"berries"},
131:{name:"Garchompite",type:"hold"},
132:{name:"Gardevoirite",type:"hold"},
133:{name:"Gengarite",type:"hold"},
134:{name:"Genius Wing",type:"medicine"},
135:{name:"Ghost Gem",type:"hold"},
136:{name:"Gooey Mulch",type:"general"},
137:{name:"Grass Gem",type:"hold"},
138:{name:"Great Ball",type:"pokeballs"},
139:{name:"Green Scarf",type:"general"},
140:{name:"Green Shard",type:"general"},
141:{name:"Grepa Berry",type:"berries"},
142:{name:"Grip Claw",type:"hold"},
143:{name:"Griseous Orb",type:"hold"},
144:{name:"Grn Apricorn",type:"general"},
145:{name:"Ground Gem",type:"hold"},
146:{name:"Growth Mulch",type:"general"},
147:{name:"Grubby Hanky",type:"hold"},
148:{name:"Guard Spec.",type:"battle"},
149:{name:"Gyaradosite",type:"hold"},
150:{name:"HP Up",type:"medicine"},
151:{name:"Haban Berry",type:"berries"},
152:{name:"Hard Stone",type:"hold"},
153:{name:"Heal Ball",type:"pokeballs"},
154:{name:"Heal Powder",type:"medicine"},
155:{name:"Health Wing",type:"medicine"},
156:{name:"Heart Scale",type:"general"},
157:{name:"Heat Rock",type:"hold"},
158:{name:"Heavy Ball",type:"pokeballs"},
159:{name:"Helix Fossil",type:"general"},
160:{name:"Heracronite",type:"hold"},
161:{name:"Holo Caster",type:"general"},
162:{name:"Hondew Berry",type:"berries"},
163:{name:"Honey",type:"general"},
164:{name:"Honor Of Kalos",type:"hold"},
165:{name:"Houndoominite",type:"hold"},
166:{name:"Hyper Potion",type:"medicine"},
167:{name:"Iapapa Berry",type:"berries"},
168:{name:"Ice Gem",type:"hold"},
169:{name:"Ice Heal",type:"medicine"},
170:{name:"Icicle Plate",type:"hold"},
171:{name:"Icy Rock",type:"hold"},
172:{name:"Insect Plate",type:"hold"},
173:{name:"Intriguing Stone",type:"hold"},
174:{name:"Iron",type:"medicine"},
175:{name:"Iron Ball",type:"hold"},
176:{name:"Iron Plate",type:"hold"},
177:{name:"Item Drop",type:"battle"},
178:{name:"Item Urge",type:"battle"},
179:{name:"Jaboca Berry",type:"berries"},
180:{name:"Kangaskhanite",type:"hold"},
181:{name:"Kasib Berry",type:"berries"},
182:{name:"Kebia Berry",type:"berries"},
183:{name:"Kelpsy Berry",type:"berries"},
184:{name:"King's Rock",type:"hold"},
185:{name:"Lagging Tail",type:"hold"},
186:{name:"Lansat Berry",type:"berries"},
187:{name:"Lava Cookie",type:"medicine"},
188:{name:"Lax Incense",type:"hold"},
189:{name:"Leaf Stone",type:"general"},
190:{name:"Leftovers",type:"hold"},
191:{name:"Lemonade",type:"medicine"},
192:{name:"Lens Case",type:"general"},
193:{name:"Leppa Berry",type:"berries"},
194:{name:"Level Ball",type:"pokeballs"},
195:{name:"Liechi Berry",type:"berries"},
196:{name:"Life Orb",type:"hold"},
197:{name:"Light Ball",type:"hold"},
198:{name:"Light Clay",type:"hold"},
199:{name:"Looker Ticket",type:"hold"},
200:{name:"Love Ball",type:"pokeballs"},
201:{name:"Lucarionite",type:"hold"},
200:{name:"Luck Incense",type:"hold"},
202:{name:"Lucky Egg",type:"hold"},
203:{name:"Lucky Punch",type:"hold"},
204:{name:"Lum Berry",type:"berries"},
205:{name:"Lure Ball",type:"pokeballs"},
206:{name:"Lustrous Orb",type:"hold"},
207:{name:"Luxury Ball",type:"pokeballs"},
208:{name:"Macho Brace",type:"hold"},
209:{name:"Magmarizer",type:"general"},
210:{name:"Magnet",type:"hold"},
211:{name:"Mago Berry",type:"berries"},
212:{name:"Magost Berry",type:"berries"},
213:{name:"Manectite",type:"hold"},
214:{name:"Master Ball",type:"pokeballs"},
215:{name:"Mawilite",type:"hold"},
216:{name:"Max Elixir",type:"medicine"},
217:{name:"Max Ether",type:"medicine"},
218:{name:"Max Potion",type:"medicine"},
219:{name:"Max Repel",type:"general"},
220:{name:"Max Revive",type:"medicine"},
221:{name:"Meadow Plate",type:"hold"},
222:{name:"Medal Box",type:"general"},
223:{name:"Medichamite",type:"hold"},
224:{name:"Mental Herb",type:"hold"},
225:{name:"Metal Coat",type:"hold"},
226:{name:"Metal Powder",type:"hold"},
227:{name:"Metronome",type:"hold"},
228:{name:"Mewtwonite X",type:"hold"},
229:{name:"Mewtwonite Y",type:"hold"},
230:{name:"Micle Berry",type:"berries"},
231:{name:"Mind Plate",type:"hold"},
232:{name:"Miracle Seed",type:"hold"},
233:{name:"Moomoo Milk",type:"medicine"},
234:{name:"Moon Ball",type:"pokeballs"},
235:{name:"Moon Stone",type:"general"},
236:{name:"Muscle Band",type:"hold"},
237:{name:"Muscle Wing",type:"medicine"},
238:{name:"Mystic Water",type:"hold"},
239:{name:"Nanab Berry",type:"berries"},
240:{name:"Nest Ball",type:"pokeballs"},
241:{name:"Net Ball",type:"pokeballs"},
242:{name:"NeverMeltIce",type:"hold"},
243:{name:"Nomel Berry",type:"berries"},
244:{name:"Normal Gem",type:"hold"},
245:{name:"Nugget",type:"general"},
246:{name:"Occa Berry",type:"berries"},
247:{name:"Odd Incense",type:"hold"},
248:{name:"Odd Keystone",type:"general"},
249:{name:"Old Amber",type:"general"},
250:{name:"Old Gateau",type:"medicine"},
251:{name:"Oran Berry",type:"berries"},
252:{name:"Oval Charm",type:"general"},
253:{name:"Oval Stone",type:"general"},
254:{name:"PP Max",type:"medicine"},
255:{name:"PP Up",type:"medicine"},
256:{name:"Pamtre Berry",type:"berries"},
257:{name:"Park Ball",type:"pokeballs"},
258:{name:"Parlyz Heal",type:"medicine"},
259:{name:"Pass Orb",type:"hold"},
260:{name:"Passho Berry",type:"berries"},
261:{name:"Payapa Berry",type:"berries"},
262:{name:"Pearl",type:"general"},
263:{name:"Pearl String",type:"general"},
264:{name:"Pecha Berry",type:"berries"},
265:{name:"Permit",type:"general"},
266:{name:"Persim Berry",type:"berries"},
267:{name:"Petaya Berry",type:"berries"},
268:{name:"Pinap Berry",type:"berries"},
269:{name:"Pink Scarf",type:"general"},
270:{name:"Pinsirite",type:"hold"},
271:{name:"Pixie Plate",type:"hold"},
272:{name:"Plasma Card",type:"hold"},
273:{name:"Plume Fossil",type:"general"},
274:{name:"Pnk Apricorn",type:"general"},
275:{name:"Poison Barb",type:"hold"},
276:{name:"Poison Gem",type:"hold"},
277:{name:"Poké Ball",type:"pokeballs"},
278:{name:"Poké Doll",type:"general"},
279:{name:"Poké Toy",type:"general"},
280:{name:"Pomeg Berry",type:"berries"},
281:{name:"Potion",type:"medicine"},
282:{name:"Power Anklet",type:"hold"},
283:{name:"Power Band",type:"hold"},
284:{name:"Power Belt",type:"hold"},
285:{name:"Power Bracer",type:"hold"},
286:{name:"Power Herb",type:"hold"},
287:{name:"Power Lens",type:"hold"},
288:{name:"Power Plant Pass",type:"general"},
289:{name:"Power Weight",type:"hold"},
290:{name:"Premier Ball",type:"Pokeballs  "},
291:{name:"Pretty Wing",type:"general"},
292:{name:"Prism Scale",type:"general"},
293:{name:"Prof's Letter",type:"hold"},
294:{name:"Protector",type:"general"},
295:{name:"Protein",type:"medicine"},
296:{name:"Psychic Gem",type:"hold"},
297:{name:"Pure Incense",type:"hold"},
298:{name:"Qualot Berry",type:"berries"},
299:{name:"Quick Ball",type:"pokeballs"},
300:{name:"Quick Claw",type:"hold"},
301:{name:"Quick Powder",type:"hold"},
302:{name:"Rabuta Berry",type:"berries"},
303:{name:"Rare Bone",type:"general"},
304:{name:"Rare Candy",type:"medicine"},
305:{name:"Rawst Berry",type:"berries"},
306:{name:"Razor Claw",type:"hold"},
307:{name:"Razor Fang",type:"hold"},
308:{name:"Razz Berry",type:"berries"},
309:{name:"Reaper Cloth",type:"general"},
310:{name:"Red Apricorn",type:"general"},
311:{name:"Red Card",type:"hold"},
312:{name:"Red Flute",type:"general"},
313:{name:"Red Scarf",type:"general"},
314:{name:"Red Shard",type:"general"},
315:{name:"Relic Band",type:"general"},
316:{name:"Relic Copper",type:"general"},
317:{name:"Relic Crown",type:"general"},
318:{name:"Relic Gold",type:"general"},
319:{name:"Relic Silver",type:"general"},
320:{name:"Relic Statue",type:"general"},
321:{name:"Relic Vase",type:"general"},
322:{name:"Repeat Ball",type:"pokeballs"},
323:{name:"Repel",type:"general"},
324:{name:"Reset Urge",type:"battle"},
325:{name:"Resist Wing",type:"medicine"},
326:{name:"Reveal Glass",type:"general"},
327:{name:"Revival Herb",type:"medicine"},
328:{name:"Revive",type:"medicine"},
329:{name:"Rindo Berry",type:"berries"},
330:{name:"Ring Target",type:"hold"},
331:{name:"Rock Gem",type:"hold"},
332:{name:"Rock Incense",type:"hold"},
333:{name:"Rocky Helmet",type:"hold"},
334:{name:"Roller Skates",type:"general"},
335:{name:"Root Fossil",type:"general"},
336:{name:"Rose Incense",type:"hold"},
337:{name:"Rowap Berry",type:"berries"},
338:{name:"Sacred Ash",type:"medicine"},
339:{name:"Safari Ball",type:"pokeballs"},
340:{name:"Salac Berry",type:"berries"},
341:{name:"Scizorite",type:"hold"},
342:{name:"Scope Lens",type:"hold"},
343:{name:"Sea Incense",type:"hold"},
344:{name:"Sharp Beak",type:"hold"},
345:{name:"Shed Shell",type:"hold"},
346:{name:"Shell Bell",type:"hold"},
347:{name:"Shiny Charm",type:"general"},
348:{name:"Shiny Stone",type:"general"},
349:{name:"Shoal Salt",type:"general"},
350:{name:"Shoal Shell",type:"general"},
351:{name:"Shock Drive",type:"hold"},
352:{name:"Shuca Berry",type:"berries"},
353:{name:"Silk Scarf",type:"hold"},
354:{name:"SilverPowder",type:"hold"},
355:{name:"Sitrus Berry",type:"berries"},
356:{name:"Skull Fossil",type:"general"},
357:{name:"Sky Plate",type:"hold"},
358:{name:"Smoke Ball",type:"hold"},
359:{name:"Smooth Rock",type:"hold"},
360:{name:"Soda Pop",type:"medicine"},
361:{name:"Soft Sand",type:"hold"},
362:{name:"Soothe Bell",type:"hold"},
363:{name:"Soul Dew",type:"hold"},
364:{name:"Spell Tag",type:"hold"},
365:{name:"Spelon Berry",type:"berries"},
366:{name:"Splash Plate",type:"hold"},
367:{name:"Spooky Plate",type:"hold"},
368:{name:"Sport Ball",type:"pokeballs"},
369:{name:"Sprinklotad",type:"general"},
370:{name:"Stable Mulch",type:"general"},
371:{name:"Star Piece",type:"general"},
372:{name:"Stardust",type:"general"},
373:{name:"Starf Berry",type:"berries"},
374:{name:"Steel Gem",type:"hold"},
375:{name:"Stick",type:"hold"},
376:{name:"Sticky Barb",type:"hold"},
377:{name:"Stone Plate",type:"hold"},
378:{name:"Sun Stone",type:"general"},
379:{name:"Super Potion",type:"medicine"},
380:{name:"Super Repel",type:"general"},
381:{name:"Sweet Heart",type:"medicine"},
382:{name:"Swift Wing",type:"medicine"},
383:{name:"TMV Pass",type:"general"},
384:{name:"Tamato Berry",type:"berries"},
385:{name:"Tanga Berry",type:"berries"},
386:{name:"Thick Club",type:"hold"},
387:{name:"Thunderstone",type:"general"},
388:{name:"Timer Ball",type:"pokeballs"},
389:{name:"TinyMushroom",type:"general"},
390:{name:"Toxic Orb",type:"hold"},
391:{name:"Toxic Plate",type:"hold"},
392:{name:"TwistedSpoon",type:"hold"},
393:{name:"Tyranitarite",type:"hold"},
394:{name:"Ultra Ball",type:"pokeballs"},
395:{name:"Up-Grade",type:"general"},
396:{name:"Venusaurite",type:"hold"},
397:{name:"Wacan Berry",type:"berries"},
398:{name:"Water Gem",type:"hold"},
399:{name:"Water Stone",type:"general"},
400:{name:"Watmel Berry",type:"berries"},
401:{name:"Wave Incense",type:"hold"},
402:{name:"Wepear Berry",type:"berries"},
403:{name:"White Flute",type:"general"},
404:{name:"White Herb",type:"hold"},
405:{name:"Wht Apricorn",type:"general"},
406:{name:"Wide Lens",type:"hold"},
407:{name:"Wiki Berry",type:"berries"},
408:{name:"Wise Glasses",type:"hold"},
409:{name:"X Accuracy",type:"battle"},
410:{name:"X Attack",type:"battle"},
411:{name:"X Defend",type:"battle"},
412:{name:"X Sp. Def",type:"battle"},
413:{name:"X Special",type:"battle"},
414:{name:"X Speed",type:"battle"},
415:{name:"Yache Berry",type:"berries"},
416:{name:"Yellow Flute",type:"general"},
417:{name:"Yellow Scarf",type:"general"},
418:{name:"Yellow Shard",type:"general"},
419:{name:"Ylw Apricorn",type:"general"},
420:{name:"Zap Plate",type:"hold"},
421:{name:"Zinc",type:"medicine"},
422:{name:"Zoom Lens",type:"hold"}
}